
trigger: none

pool:
  vmImage: ubuntu-latest

jobs:
 - job: myJob
   displayName: MyfirstJob
   steps:
   - script: echo Mynew Job
 - job: newJob
   displayName: newJob
   steps:
   - script: echo 'hello again, welcome to shell classes'
   - script: 'date;ls;pwd;uname; whoami'