
trigger: none

pool:
  vmImage: ubuntu-18.04
  demands: maven

steps:
- task: Maven@3
  displayName: 'Maven pom.xml'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    Contents: '**/*.war'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: myartifact'
  inputs:
    ArtifactName: myartifact
