
trigger: none

pool:
  vmImage: ubuntu-latest


jobs:
 - job: myJob
   steps:
   - checkout: self
     fetchDepth: 0
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sn2'
    organization: 'ecom23'
    scannerMode: 'Other'
    extraProperties: |
      # Additional properties that will be passed to the scanner,
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.projectKey=ecom23_newproject23
      sonar.projectName=newproject23
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'